-- 1-WRONG --
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION;
SELECT * FROM Producatori WHERE cod_p BETWEEN 1 AND 100;
WAITFOR DELAY '00:00:07';
SELECT * FROM Producatori WHERE cod_p BETWEEN 1 AND 100;
COMMIT TRAN;


-- 1-SOLUTION -- schimbam nivelul de izolare la SERIALIZABLE pentru a arata de fiecare data aceleasi date
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
SELECT * FROM Producatori WHERE cod_p BETWEEN 1 AND 100;
WAITFOR DELAY '00:00:07'
SELECT * FROM Producatori WHERE cod_p BETWEEN 1 AND 100;
COMMIT TRANSACTION
DELETE FROM Producatori WHERE nume_p='A'



-- 2 --
BEGIN TRANSACTION
WAITFOR DELAY '00:00:05'
INSERT INTO Producatori(nume_p, website) VALUES ('A', 'A');
COMMIT TRANSACTION